### PR TITLE
Allow search in dropdowns

### LINKED ISSUE #125: Keyboard Entry Not Working
I also tried entering surveys for West Barnstable Elementary on the new site, after creating a new survey instance, I used the batch entry. The form is not responsive to the keyboard. I should be able to hit “F” and have it select Family Vehicle, “S” school bus, and so on and so forth throughout the form. This feature makes entering stacks of paper surveys take no time at all. Thanks for adding this to your list.

### PR DESCRIPTION
**Pull request by allthesignals**
Closes #125

## Description
This PR enables keyboard entry for selection in dropdowns.

## Reviewer Note: Did I run `rails test` and 100% passing tests before merging?
nope

### CODE REVIEW

**Comment by allthesignals** [comment]
@mzagaja

**Comment by mzagaja** [comment]
This works great, but wondering why the survey id is in an unlabeled drop down at the bottom instead of pre-populated in a hidden field? Not sure if this is related to this update or a different issue. If it's different then I'll accept this and open a new issue for that.

screen shot 2017-08-07 at 1 46 28 pm

**Comment by allthesignals** [comment]
@mzagaja I think because batch entry can be for any given survey, there's a way to select which survey it adds to. This is the [existing functionality](http://masaferoutessurvey.org/en/lynn/aborn/batch/), which I chose to rebuild. If you want to open a separate issue for it, go for it, but I don't think it's part of the tasks I'm committed to. 

Also, I'm sorry it's unlabeled. I think you can label it in a plain Rails view here: https://github.com/MAPC/myschoolcommute2/blob/68bdd54fa220ddcfd3894f7939b4229530807500/app/views/survey_responses/new.html.erb.

**Comment by mzagaja** [comment]
@allthesignals ok that makes sense, I'll just clean it up in the view then. I think it was just not obvious to the user.

**Pull request merged**
