### PR TITLE
Rework layout for welcome page

### PR DESCRIPTION
**Pull request by ericyoungberg**

### CODE REVIEW

**Comment by mzagaja** [comment]
screen shot 2017-09-12 at 2 12 01 pm

Looks good on desktop, but wondering if on mobile it would make sense to have full-width content boxes instead of side by side?

**Comment by ericyoungberg** [comment]
I didn't build in breakpoints because of the budget constraint (tried to take as little time as possible) and most of the rest of the site isn't responsive so I assumed that we weren't building with that in mind. I can easily add in some breakpoints if I'm allowed the time. @arouault ?

**Comment by arouault** [comment]
Breakpoints are ideal but is it possible to deploy as is and do these after you get back @ericyoungberg important to transition over this week.

**Comment by ericyoungberg** [comment]
Yeah I can add breakpoints once I'm back or if I get a chance to sometime this week/weekend. I normally wake up earlier than everyone else.

**Pull request merged**
