### PR TITLE
Fix input name issue

### PR DESCRIPTION
**Pull request by allthesignals**
## Description
Addresses #130

### CODE REVIEW

**Comment by mzagaja** [comment]
@allthesignals just wondering if you have a timeline on pushing this fix since it's blocking a few things on my end

**Comment by allthesignals** [comment]
@mzagaja there's a new PR here: https://github.com/MAPC/myschoolcommute2/pull/132

Why are you blocked on this?

**Comment by mzagaja** [comment]
@allthesignals thanks I'll take a look. Having this working is a prerequisite to being able to test my solution to #89.

**Comment by arouault** [comment]
@allthesignals Making sure you saw Zagaja's note -- as he can't move forward until this works. Thank you!

**Pull request merged**
